openapi: 3.0.4
info:
  title: Movie Recommendation API
  description: Unified API specification.
  version: 1.0.0

servers:
  - url: http://localhost:4000/api/v1
    description: Local dev

paths: {}
